import type { WaterType } from "../../models/waterLocation";

/**
 * Fishing spots from the owner's own list (local, county and state parks,
 * public fishing areas, ramps and marinas across Georgia). Coordinates were
 * looked up on OpenStreetMap and checked against each spot's county; spots
 * placed only by road or town are tagged "Approx. location". Spots whose
 * fishing isn't confirmed are tagged "Fishing unconfirmed".
 *
 * Not yet placed (no map match): Pilot Park and McGarity Park (Walton),
 * Ocmulgee PFA (Bleckley), Gillis PFA (Laurens). Add them here with
 * coordinates once known.
 */
export type GuideSpot = {
  id: string;
  name: string;
  type: WaterType;
  water?: ("lake" | "river")[];
  latitude: number;
  longitude: number;
  facts: string[];
};
export const GUIDE_SPOTS: GuideSpot[] = [
  {
    id: "guide-mathews-park",
    name: "Mathews Park",
    type: "park",
    water: ["lake"],
    latitude: 33.81764,
    longitude: -83.70275,
    facts: ["Fishing unconfirmed", "~3-acre lake", "Call 770-267-7525"],
  },
  {
    id: "guide-hard-labor-creek-sp",
    name: "Hard Labor Creek State Park",
    type: "park",
    water: ["lake"],
    latitude: 33.64890542,
    longitude: -83.59038388,
    facts: [
      "Fishing allowed",
      "License 16+",
      "Lake Rutledge 275 ac",
      "Lake Brantley 48 ac",
      "Motors ≤10 HP",
      "Bass, stripers, catfish, crappie, bluegill",
      "Call 706-557-3001",
    ],
  },
  {
    id: "guide-lake-varner",
    name: "Lake Varner",
    type: "reservoir",
    latitude: 33.64865,
    longitude: -83.79592,
    facts: ["Fishing allowed", "Bank fishing", "ADA pier", "Boat ramp"],
  },
  {
    id: "guide-factory-shoals-park",
    name: "Factory Shoals Park",
    type: "park",
    water: ["river"],
    latitude: 33.44673,
    longitude: -83.8283,
    facts: ["Fishing allowed", "River shoals"],
  },
  {
    id: "guide-lake-oconee",
    name: "Lake Oconee",
    type: "reservoir",
    latitude: 33.50459,
    longitude: -83.28278,
    facts: ["Fishing allowed", "19,971 acres"],
  },
  {
    id: "guide-sugar-creek-marina",
    name: "Sugar Creek Marina",
    type: "boat-ramp",
    latitude: 33.54005,
    longitude: -83.31509,
    facts: [
      "Private marina",
      "Bait & tackle",
      "Ramp",
      "Lake Oconee",
      "Call 706-342-2231",
      "Approx. location",
    ],
  },
  {
    id: "guide-blue-springs-marina",
    name: "Blue Springs Marina",
    type: "boat-ramp",
    latitude: 33.53861,
    longitude: -83.29029,
    facts: [
      "Private marina",
      "Lake Oconee",
      "Call 706-342-9446",
      "Approx. location",
    ],
  },
  {
    id: "guide-swords-boat-ramp",
    name: "Swords Boat Ramp",
    type: "boat-ramp",
    latitude: 33.54429,
    longitude: -83.30683,
    facts: ["Fishing allowed", "Lake Oconee", "Approx. location"],
  },
  {
    id: "guide-apalachee-mart",
    name: "Apalachee Mart",
    type: "fishing-spot",
    latitude: 33.59052,
    longitude: -83.36215,
    facts: [
      "Pay to fish",
      "Day passes",
      "Apalachee River",
      "Call 706-474-2695",
      "Approx. location",
    ],
  },
  {
    id: "guide-sandy-creek-park",
    name: "Sandy Creek Park",
    type: "park",
    water: ["lake"],
    latitude: 34.03648,
    longitude: -83.38429,
    facts: [
      "Fishing allowed",
      "License required",
      "Lake Chapman 260 ac",
      "No fishing near dam, spillway, beach or ramp",
      "Call 706-613-3800",
    ],
  },
  {
    id: "guide-ben-burton-park",
    name: "Ben Burton Park",
    type: "park",
    water: ["river"],
    latitude: 33.96019,
    longitude: -83.43907,
    facts: ["Fishing allowed", "Middle Oconee River", "Non-motorized launch"],
  },
  {
    id: "guide-memorial-park-athens",
    name: "Memorial Park (Athens)",
    type: "pond",
    latitude: 33.92678,
    longitude: -83.38689,
    facts: [
      "Fishing allowed",
      "Stocked pond",
      "Bream, catfish",
      "License required",
    ],
  },
  {
    id: "guide-dudley-park",
    name: "Dudley Park",
    type: "park",
    water: ["river"],
    latitude: 33.95635,
    longitude: -83.36628,
    facts: ["Fishing allowed", "North Oconee River"],
  },
  {
    id: "guide-lake-herrick",
    name: "Lake Herrick",
    type: "lake",
    latitude: 33.93059,
    longitude: -83.37178,
    facts: ["Fishing allowed", "UGA-managed: check rules"],
  },
  {
    id: "guide-rocky-mountain-pfa",
    name: "Rocky Mountain PFA",
    type: "park",
    water: ["lake"],
    latitude: 34.35565,
    longitude: -85.30398,
    facts: [
      "Public fishing area",
      "2 lakes, 559 ac",
      "No night fishing",
      "Approx. location",
    ],
  },
  {
    id: "guide-big-lazer-creek-pfa",
    name: "Big Lazer Creek PFA",
    type: "park",
    water: ["lake"],
    latitude: 32.78261,
    longitude: -84.40638,
    facts: ["Public fishing area", "195-acre lake"],
  },
  {
    id: "guide-dodge-county-pfa",
    name: "Dodge County PFA",
    type: "park",
    water: ["lake"],
    latitude: 32.15797,
    longitude: -83.13142,
    facts: ["Public fishing area", "104-acre lake"],
  },
  {
    id: "guide-evans-county-pfa",
    name: "Evans County PFA",
    type: "park",
    water: ["lake"],
    latitude: 32.12703,
    longitude: -81.80203,
    facts: ["Public fishing area", "3 lakes, 8–84 ac", "Approx. location"],
  },
  {
    id: "guide-flat-creek-pfa",
    name: "Flat Creek PFA",
    type: "park",
    water: ["lake"],
    latitude: 32.40926,
    longitude: -83.77155,
    facts: ["Public fishing area", "102-acre lake"],
  },
  {
    id: "guide-silver-lake-pfa",
    name: "Silver Lake PFA",
    type: "park",
    water: ["lake"],
    latitude: 30.8028,
    longitude: -84.72394,
    facts: ["Public fishing area", "30+ lakes, 537 ac"],
  },
  {
    id: "guide-mcduffie-pfa",
    name: "McDuffie PFA",
    type: "park",
    water: ["lake"],
    latitude: 33.39486,
    longitude: -82.42346,
    facts: ["Public fishing area", "7 lakes, 5–37 ac"],
  },
  {
    id: "guide-red-top-mountain-sp",
    name: "Red Top Mountain State Park",
    type: "park",
    water: ["lake"],
    latitude: 34.14676,
    longitude: -84.70765,
    facts: ["Fishing allowed", "Lake Allatoona"],
  },
  {
    id: "guide-georgia-veterans-sp",
    name: "Georgia Veterans State Park",
    type: "park",
    water: ["lake"],
    latitude: 31.95887,
    longitude: -83.90346,
    facts: ["Fishing allowed", "Lake Blackshear"],
  },
  {
    id: "guide-moccasin-creek-sp",
    name: "Moccasin Creek State Park",
    type: "park",
    water: ["lake"],
    latitude: 34.84616,
    longitude: -83.58733,
    facts: ["Fishing allowed", "Lake Burton"],
  },
  {
    id: "guide-elijah-clark-sp",
    name: "Elijah Clark State Park",
    type: "park",
    water: ["lake"],
    latitude: 33.8538,
    longitude: -82.40373,
    facts: ["Fishing allowed", "Clarks Hill Lake"],
  },
  {
    id: "guide-mistletoe-sp",
    name: "Mistletoe State Park",
    type: "park",
    water: ["lake"],
    latitude: 33.65122,
    longitude: -82.385,
    facts: ["Fishing allowed", "Clarks Hill Lake"],
  },
  {
    id: "guide-hart-sp",
    name: "Hart State Park",
    type: "park",
    water: ["lake"],
    latitude: 34.37788,
    longitude: -82.91236,
    facts: ["Fishing allowed", "Lake Hartwell"],
  },
  {
    id: "guide-tugaloo-sp",
    name: "Tugaloo State Park",
    type: "park",
    water: ["lake"],
    latitude: 34.49688,
    longitude: -83.06253,
    facts: ["Fishing allowed", "Lake Hartwell"],
  },
  {
    id: "guide-don-carter-sp",
    name: "Don Carter State Park",
    type: "park",
    water: ["lake"],
    latitude: 34.39011,
    longitude: -83.74615,
    facts: ["Fishing allowed", "Lake Lanier"],
  },
  {
    id: "guide-russell-sp",
    name: "Richard B. Russell State Park",
    type: "park",
    water: ["lake"],
    latitude: 34.16784,
    longitude: -82.7411,
    facts: ["Fishing allowed", "Lake Russell"],
  },
  {
    id: "guide-bagby-sp",
    name: "George T. Bagby State Park",
    type: "park",
    water: ["lake"],
    latitude: 31.6662,
    longitude: -85.05619,
    facts: ["Fishing allowed", "Lake Walter F. George"],
  },
  {
    id: "guide-high-falls-sp",
    name: "High Falls State Park",
    type: "park",
    latitude: 33.17831,
    longitude: -84.01594,
    facts: ["Fishing allowed"],
  },
  {
    id: "guide-florence-marina-sp",
    name: "Florence Marina State Park",
    type: "park",
    latitude: 32.09322,
    longitude: -85.04345,
    facts: ["Fishing allowed"],
  },
  {
    id: "guide-walker-sp",
    name: "Laura S. Walker State Park",
    type: "park",
    water: ["lake"],
    latitude: 31.14105,
    longitude: -82.21472,
    facts: ["Fishing allowed", "120-acre lake"],
  },
  {
    id: "guide-vogel-sp",
    name: "Vogel State Park",
    type: "park",
    latitude: 34.76294,
    longitude: -83.92843,
    facts: ["Fishing allowed"],
  },
  {
    id: "guide-foster-sp",
    name: "Stephen C. Foster State Park",
    type: "park",
    latitude: 30.82322,
    longitude: -82.3648,
    facts: ["Fishing allowed"],
  },
  {
    id: "guide-seminole-sp",
    name: "Seminole State Park",
    type: "park",
    latitude: 30.8041,
    longitude: -84.86763,
    facts: ["Fishing allowed"],
  },
  {
    id: "guide-sweetwater-creek-sp",
    name: "Sweetwater Creek State Park",
    type: "park",
    latitude: 33.75446,
    longitude: -84.62986,
    facts: ["Fishing allowed"],
  },
];

/** Extra facts for spots that were already in the app. */
export const EXTRA_FACTS: Record<string, string[]> = {
  "alltrails-10022765": [
    "License 16+",
    "Marbury Creek Reservoir 260 ac",
    "Motors ≤10 HP",
    "Open year-round",
  ],
  "alltrails-11078971": [
    "Marben Farms PFA: 20 ponds",
    "License or Lands Pass",
    "Night fishing OK",
  ],
  "alltrails-10474632": ["Call 770-786-4373"],
  "alltrails-10280108": [
    "Free admission",
    "Non-motorized boats",
    "Ramp",
    "Call 678-277-0890",
  ],
  "alltrails-10304710": ["Open sunrise–11 PM", "Call 678-277-0890"],
};
